spring:
  application:
    name: UCBackend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?createDatabaseIfNotExist=true
    username: root
    password: 15723375
  sql:
    init:
      mode: always
      schema-locations: "classpath:database-init.sql"
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liWN6QmqOJL3bTjq
            client-secret: c638fd3ed33385a9b8e646f2b41cc8c4d426a592
server:
  port: 8080